### ISSUE TITLE
looks useful but get cannot find python3

### ISSUE THREAD

**Issue by tobidelbruck** [GeorgiosDrivas/vscode-docs-official#4] opened 2024-10-20 05:56 UTC
![2024-10-20_075438](https://github.com/user-attachments/assets/e4fd5b1b-ed13-4b14-8e3f-3fd3af31424a)

I definitely have a python3 defined as my conda env for the current workspace and can run e.g. matplotlib in jupyter notebook. This is on windows11 latest vsdocde 1.94.2

**Comment by GeorgiosDrivas** [comment] 2024-10-20 08:21
@tobidelbruck Hello and thank you for your time commenting on this project! I will check the issue today and inform you when it's done.

**Comment by GeorgiosDrivas** [comment] 2024-10-20 11:21
Dear Tobi Delbruck @tobidelbruck,

After thoroughly reviewing your issue, I have determined that there does not appear to be any error in the extension, as indicated in the provided screenshot. It is likely that the issue arises from another part of your codebase.

To further verify this, I set up a project using Python 3 to manually test the extension, and it functioned as expected. The "Docs Official" extension successfully opens the documentation for the currently selected file in the browser.

I recommend ensuring that you are using the latest version of the extension and that there are no other errors in your codebase. If the issue persists and is related to the extension, please feel free to provide additional feedback, and I will make every effort to assist in resolving it.

**Comment by tobidelbruck** [comment] 2024-10-20 18:08
Thanks for looking. In vscode, I will try 
https://stackoverflow.com/questions/44188262/where-are-the-vscode-error-logs-for-extensions 
to see what is the error.

**Comment by tobidelbruck** [comment] 2024-10-20 18:12
Here is the logging output:

![2024-10-20_201057](https://github.com/user-attachments/assets/1f0ac192-ee3f-4375-b185-c5f7f781f502)

In my vscode terminal, I have python:
 
![2024-10-20_201208](https://github.com/user-attachments/assets/09cd0b40-4a9d-44b5-b086-6091710cf475)

I don't get it...

**Comment by GeorgiosDrivas** [comment] 2024-10-20 18:17
Are you sure this error is caused by the Docs Official extension? Please disable the extension and try again because no such error seems to happen when using the Docs Official extension.

**Closed** 2024-10-31 09:44 UTC
